apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: example-selfsigned-cluster-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: example.com
  secretName: ca-tls
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
  issuerRef:
    name: example-selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
    
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: example-intermicrosvccom-ca-issuer
spec:
  ca:
    secretName: ca-tls
